spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sim?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 2
      max-active: 2
    jmx-enabled: true

  redis:
    host: 106.14.185.58
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200 # 最大连接数 （使用负值表示没有限制）
        max-wait: 1  # 最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 最大空闲连接
        min-idle: 0
    timeout: 1000
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


